# -*- encoding: utf-8 -*-
"""
vLEI Verification Servcie
verifier.core.basing module

Database support
"""
from keri.core import coring
from keri.db import dbing, subing


class VerifierBaser(dbing.LMDBer):
    """
    Noter stores Notifications generated by the agent that are
    intended to be read and dismissed by the controller of the agent.

    """
    TailDirPath = "keri/vdb"
    AltTailDirPath = ".verifier/vdb"
    TempPrefix = "keri_vdb_"

    def __init__(self, name="vdb", headDirPath=None, reopen=True, **kwa):
        """

        Parameters:
            headDirPath:
            perm:
            reopen:
            kwa:
        """
        self.snd = None

        self.iss = None
        self.rev = None

        self.accts = None
        self.revk = None

        self.imgs = None

        super(VerifierBaser, self).__init__(name=name, headDirPath=headDirPath, reopen=reopen, **kwa)

    def reopen(self, **kwa):
        """

        :param kwa:
        :return:
        """
        super(VerifierBaser, self).reopen(**kwa)

        # Database of senders of the presentation or revocation messages
        self.snd = subing.CesrSuber(db=self, subkey='snd.', klas=coring.Prefixer)

        # presentations that are waiting for the credential to be received and parsed
        self.iss = subing.CesrSuber(db=self, subkey='iss.', klas=coring.Dater)

        # revocations that are waiting for the TEL event to be received and processed
        self.rev = subing.CesrSuber(db=self, subkey='rev.', klas=coring.Dater)

        # presentations with resolved credentials that need to be sent to the hook
        self.accts = subing.CesrSuber(db=self, subkey='accts', klas=coring.Saider)

        # Chunked file data for uploaded reports
        self.imgs = self.env.open_db(key=b'imgs.')

        return self.env
